### ISSUE TITLE
Invalid paramter

### ISSUE THREAD

**Issue by peternavr** [josmo/drone-elastic-beanstalk#7]
InvalidParameterCombination: Unable to download from S3 location (Bucket: XXX  Key: XXX). Reason: Not Found

the same account has access to both ELB and S3 via policy.

```
deploy:
  elastic_beanstalk:
    access_key: [account key]
    secret_key: [account secret key]
    region: us-west-2
    version_label: v1
    bucket_name: [env's bucket name]
    application: [env name]
    bucket_key: [account secret key]
```
